#!/usr/bin/python

import yaml

docs='''
    - foo.service: 
        Unit:
            Description: Foo

        Service:
            ExecstartPre: /usr/sbin/foo-prev
            Execstart: /usr/sbin/foo-daemon -v
        Install:
            WantedBy: multi-user.target
    '''

systemd_units = yaml.load(docs)

for unit in systemd_units:
    for unit_name in unit:
        print 'unit file: ', unit_name 
        f = file(unit_name, 'w')
        sections = unit[unit_name]
        #print sections
        for sec in sections:
            secstr = '[%s]\n' % sec
            #print secstr
            f.write(secstr)
            options = sections[sec]
            for opt in options:
                optstr = '%s=%s\n' % (opt, options[opt])
                #print optstr
                f.write(optstr)
            #print '\n',
            f.write('\n')
        f.close()
        #print 'section: ', section
        #for option in section:
        #    print option
